Work section
Ngufor-emmanuella/first-micro-project pull request #2
Opened 2022-05-28 17:51 UTC by Ngufor-emmanuella

In this project I created a portfolio showing my skillls in
-HTML as the language
-used CSS to design my webpage
-used css grid and flex box to align my elements 
-and linters to check my codes

2022-05-28 20:53 UTC, danielufeli requested changes
Hi @Ngufor-emmanuella , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has an unprofessional readme, Kindly update your readme to be more professional using the [Readme Template](https://github.com/microverseinc/readme-template)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-05-28 22:56 UTC, Kakalanp requested changes
# Hello there @Ngufor-emmanuella! <img src="https://user-images.githubusercontent.com/1303154/88677602-1635ba80-d120-11ea-84d8-d263ba5fc3c0.gif" width="28px" alt="hi">

### Good job so far! :tada: 

You still need to work on some issues to go to the next project, but you are almost there! :pinching_hand: 

<img src="https://media.giphy.com/media/Qaxd5XpgDWMso/giphy.gif" alt="so close">

## Highlights :+1: 
- No linter errors :heavy_check_mark:
- Repo looks professional :briefcase:
- Solid pull request :scroll:
- Mostly followed best practices :monocle_face: 

## Required Changes ♻️
***Check the comments under the review.***

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-28 22:56 UTC, Kakalanp commented on style.css
> +}
Try aligning the items inside the _second_ class with flexbox :nerd_face:

2022-05-28 22:56 UTC, Kakalanp commented on index.html
> +                </div>
Great work of `<ul>` and `<li>` on frameworks and skill, but remember languages is also part of that list (a nested list), so kindly add it to the `<ul>` as a `<li>` too :fire:

2022-05-28 22:56 UTC, Kakalanp commented on style.css
> +}
Also, a recommendation to keep your design closer to the Figma version could be:
```
margin: 15px auto;
max-width: 90%;
```

2022-05-28 22:56 UTC, Kakalanp commented on style.css
>  }
[OPTIONAL]

Your background image seems to make this paragraph difficult to read 
![image](https://user-images.githubusercontent.com/78335447/170845177-38f18353-65de-4ded-a9cf-26496e56cf00.png)

I'd advice you to add the background image to the container of your presentation to fix it :wink:

2022-05-28 22:56 UTC, Kakalanp commented on README.md
>  First-micro-project
Great work fixing this one while I finished your review! :smiley:

2022-06-02 09:07 UTC, Ngufor-emmanuella commented
thank you

2022-06-02 09:07 UTC, merged